[package]
name = "restapi"
version = "0.1.0"
authors = ["Hien D. Pham <dhiefphams@gmail.com>"]

[dependencies]
nickel="*"
rustc-serialize = "*"
mongodb = "*"
bson = "*"
serde_json="*"
serde_derive="*"
serde="*"
jwt = "*"
hyper = "*"
rust-crypto = "*"